### ISSUE TITLE
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888

### ISSUE THREAD

**Issue by mobin-sk** [dadagov125/flutter_scan_tools#2]
Whenever camera is opened in iOS , App got crashed.

`The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
[VERBOSE-3:platform_message_handler_ios.mm(106)] Check failed: task_runners_.GetPlatformTaskRunner()->RunsTasksOnCurrentThread().
* thread #7, queue = 'io.flutter.camera.dispatchqueue', stop reason = signal SIGABRT
    frame #0: 0x00000001dad1f160 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1dad1f160 <+8>:  b.lo   0x1dad1f180               ; <+40>
    0x1dad1f164 <+12>: pacibsp 
    0x1dad1f168 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1dad1f16c <+20>: mov    x29, sp
Target 0: (Runner) stopped.`

**Comment by mobin-sk** [comment]
Please update camera plugin & release new version, I hope it will solve this issue

**Comment by dadagov125** [comment]
Hello!
Thanks for the information. We'll fix it soon!

**Comment by dadagov125** [comment]
fixed on 0.0.3 version
