### ISSUE TITLE
crash on iPhone 6s

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [dadagov125/flutter_scan_tools#5]
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
flutter: >>>>>> Scan Start
Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=1450 MB, unused=0x0)
    frame #0: 0x00000001f1775138 libsystem_platform.dylib`_platform_memmove + 88
libsystem_platform.dylib`_platform_memmove:
->  0x1f1775138 <+88>:  stnp   x8, x9, [x3]
    0x1f177513c <+92>:  stnp   x10, x11, [x3, #0x10]
    0x1f1775140 <+96>:  add    x3, x3, #0x20
    0x1f1775144 <+100>: ldnp   x8, x9, [x1]
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by dadagov125** [comment]
Hello! 
Does the error throw only in version 0.0.2?
Can you check for version 0.0.3?
